export default `<!DOCTYPE html><html lang="en" data-beasties-container><head>
  <meta charset="utf-8">
  <title>OmegaCorpFrontend</title>
  <base href="https://patriickdoyle.github.io/dev/omega-corp-frontend/">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
<link rel="stylesheet" href="styles-5INURTSO.css"><style ng-app-id="ng">body[_ngcontent-ng-c3297372441]{font-family:Arial,sans-serif;display:flex;justify-content:center;align-items:center;height:100vh;margin:0;background-color:#f4f4f4}.title-container[_ngcontent-ng-c3297372441]{text-align:center}.main-title[_ngcontent-ng-c3297372441]{font-size:3em;color:#333;margin:0}.subtitle[_ngcontent-ng-c3297372441]{font-size:1.5em;color:#666;margin:.5em}</style><style ng-app-id="ng">nav[_ngcontent-ng-c1824832383]{background-color:#333;padding:1em}ul[_ngcontent-ng-c1824832383]{list-style-type:none;margin:0;padding:0;display:flex;justify-content:space-around}li[_ngcontent-ng-c1824832383]{margin:0}a[_ngcontent-ng-c1824832383]{color:#fff;text-decoration:none;font-size:1.2em}a[_ngcontent-ng-c1824832383]:hover{text-decoration:underline}</style></head>
<body><!--nghm--><script type="text/javascript" id="ng-event-dispatch-contract">(()=>{function p(t,n,r,o,e,i,f,m){return{eventType:t,event:n,targetElement:r,eic:o,timeStamp:e,eia:i,eirp:f,eiack:m}}function u(t){let n=[],r=e=>{n.push(e)};return{c:t,q:n,et:[],etc:[],d:r,h:e=>{r(p(e.type,e,e.target,t,Date.now()))}}}function s(t,n,r){for(let o=0;o<n.length;o++){let e=n[o];(r?t.etc:t.et).push(e),t.c.addEventListener(e,t.h,r)}}function c(t,n,r,o,e=window){let i=u(t);e._ejsas||(e._ejsas={}),e._ejsas[n]=i,s(i,r),s(i,o,!0)}window.__jsaction_bootstrap=c;})();
</script><script>window.__jsaction_bootstrap(document.body,"ng",["click"],[]);</script>
  <app-root ng-version="19.1.0" ngh="1" ng-server-context="ssg"><app-title _nghost-ng-c3297372441 ngh="0"><div _ngcontent-ng-c3297372441 class="title-container"><h1 _ngcontent-ng-c3297372441 class="main-title">Omega Corporation</h1><h2 _ngcontent-ng-c3297372441 class="subtitle">Pennsylvania Home Improvement Contractor</h2></div></app-title><app-nav-bar _nghost-ng-c1824832383 ngh="0"><nav _ngcontent-ng-c1824832383><ul _ngcontent-ng-c1824832383><li _ngcontent-ng-c1824832383><a _ngcontent-ng-c1824832383 routerlink="/" href="https://patriickdoyle.github.io/dev/omega-corp-frontend/" jsaction="click:;">About Us</a></li><li _ngcontent-ng-c1824832383><a _ngcontent-ng-c1824832383 routerlink="/contact-us" href="https://patriickdoyle.github.io/dev/omega-corp-frontend/contact-us" jsaction="click:;">Contact Us</a></li></ul></nav></app-nav-bar><router-outlet></router-outlet><!----></app-root>
<script src="polyfills-FFHMD2TL.js" type="module"></script><script src="main-RT3M7MXY.js" type="module"></script>

<script id="ng-state" type="application/json">{"__nghData__":[{},{"c":{"2":[]}}]}</script></body></html>`;